GPUS: (0,) #(0,1,2,3)
WORKERS: 2 #4
PRINT_FREQ: 20

DATASET:
  DATASET: ped2
  ROOT: '/content/drive/MyDrive/datasets'
  NUM_FRAMES: 5
  FRAME_STEPS: 2
  LOWER_BOUND: 100

TRAIN:
  BATCH_SIZE_PER_GPU: 2
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 40
  RESUME: false
  #CHECKPOINT: '/content/astnet/ASTNet/output/ped2/ped2_wresnet/epoch_33.pth'
  OPTIMIZER: 'adam'
  LR_TYPE: 'multistep'
  LR: 0.0002
  LR_STEP: [50, 65]

TEST:
  BATCH_SIZE_PER_GPU: 1

MODEL:
  NAME: 'wrn38'
  INIT_WEIGHTS: true
  PRETRAINED: '/content/astnet/ASTNet/datasets/seg_weights/wider_resnet38.pth'
  IMAGE_SIZE:
    - 224
    - 288
  MEMORY_SIZE: 5
  ENCODED_FRAMES: 4
  DECODED_FRAMES: 0
  EXTRA:
    FINAL_CONV_KERNEL: 3
