GPUS: (0,) #(0,1,2,3)
WORKERS: 4 #2 
PRINT_FREQ: 20
SAVE_CHECKPOINT_FREQ: 1

DATASET:
  DATASET: synth #split_80-20-20_astnet
  ROOT: '/content/astnet/data/' #'/content/drive/MyDrive/datasets/Synth'
  NUM_FRAMES: 5 #5-1: frames persi per ogni video
  FRAME_STEPS: 5 #da 2->5: finestra da 5 frames diminuendo le tempistiche
  LOWER_BOUND: 0

TRAIN:
  BATCH_SIZE_PER_GPU: 4 #2
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 50
  RESUME: true #inserire true solo se si vuole partire da qualche checkpoint
  CHECKPOINT: '/content/astnet/ASTNet/output/synth/synth_wresnet/epoch_10.pth'
  OPTIMIZER: 'adam'
  LR_TYPE: 'multistep'
  LR: 0.0002
  LR_STEP: [30,40] #[80,100]

TEST:
  BATCH_SIZE_PER_GPU: 1

MODEL:
  NAME: 'wrn38'
  INIT_WEIGHTS: true
  PRETRAINED: '/content/astnet/ASTNet/datasets/seg_weights/wider_resnet38.pth'
  IMAGE_SIZE:
    - 224
    - 288
  MEMORY_SIZE: 5
  ENCODED_FRAMES: 4
  DECODED_FRAMES: 0
  EXTRA:
    FINAL_CONV_KERNEL: 3
